name: Server
main: com.StravitZone.Core.Main
version: 1.0
author: Janitored_
commands:
    rank:
        description: Set a player's rank
    ban:
        description: Ban a player w/ reason
    kick:
        description: Kick a player w/ reason
    mute:
        description: Mute a player w/ reason
    unban:
        description: Unban a player
    unmute:
        description: Unmute a player
    restore:
        description: Restore your admin rank
    addworld:
        description: Create a world
    tpworld:
        description: TP to a world
    broadcast:
        description: Broadcast a message
        aliases: [bc]
    lockchat:
        description: lock the chat
    clearchat:
        description: clear the chat
    game:
        description: Plugin information
    giveaway:
        description: Begin a giveaway
    tutorial:
        description: SZ Tutorial